CREATE SCHEMA IBM_CONFIRMING;

CREATE TABLE IF NOT EXISTS IBM_CONFIRMING.PROVEEDORES(
	ID_PROVEEDOR INTEGER NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    FECHA_ALTA DATE NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID_PROVEEDOR)
);

INSERT INTO IBM_CONFIRMING.PROVEEDORES VALUES(
	1,
    'Coca-cola',
    '2022-06-01',
    5
);

INSERT INTO IBM_CONFIRMING.PROVEEDORES VALUES(
	2,
    'Pepsi',
    '2022-06-01',
    5
);

INSERT INTO IBM_CONFIRMING.PROVEEDORES VALUES(
	3,
    'Redbull',
    '2022-06-01',
    6
);

#Sentencia para filtrar proveedores por el id del cliente (5 como ejemplo)
SELECT * FROM proveedores WHERE id_cliente = 5
